name: Android CI

on:
  push:
    branches: [ "master" ] # TODO: On any branch
  pull_request:
    branches: [ "master" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Merge feature branches
      run: ./script/merge-feature-branches

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Build with Gradle
      #run: ./gradlew build
      #run: ./gradlew assembleRelease
      run: ./gradlew assembleCiRelease
    # TODO
    #- store_artifacts:
    #  path: app/build/outputs/apk
    #  destination: outputs

  lint:
    runs-on: ubuntu-latest
    needs: build # TODO Try to depend on setup only
    steps:
    - name: Static Analysis
      run: ./gradlew lint
    # TODO
    #- store_artifacts:
    #  path: app/build/reports
    #  destination: outputs

  test:
    runs-on: ubuntu-latest
    needs: build # TODO Try to depend on setup only
    steps:
    - name: Run Tests
      run: ./gradlew test
    # TODO
    #- store_test_results:
    #  path: app/build/test-results
    #  destination: outputs

