name: Android CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Merge feature branches
      run: ./script/merge-feature-branches

    - name: Build application
      #run: ./gradlew build
      #run: ./gradlew assembleRelease
      run: ./gradlew assembleCiRelease
    - name: Archive APKs
      uses: actions/upload-artifact@v3
      with:
        #name: outputs-apk
        path: app/build/outputs/apk/**/*.apk

    - name: Run tests
      run: ./gradlew testCiRelease # TODO Dont run tests on all build variant
    - name: Archive test results
      uses: actions/upload-artifact@v3
      with:
        name: outputs-tests
        path: app/build/test-results

    - name: Static analysis
      run: ./gradlew lint # TODO Dont run lint on all build variant
    - name: Archive lint results
      uses: actions/upload-artifact@v3
      with:
        #name: outputs-lint
        path: app/build/reports/lint-*

